% Create a rectangularArray with patchMicrostrip element.
% Generated by MATLAB(R) 9.9 and Antenna Toolbox 4.3.
% Generated on: 04-Oct-2021 14:29:06

%% Array Properties 
%Define Array
arrayObject = rectangularArray;

%arrayObject.Size = [4  4];
arrayObject.Size = [8  8]; % my modification

%Define Array Elements
Element1 = patchMicrostrip;
arrayObject.Element = [Element1 ];

% Design array at frequency 8000000000Hz
arrayObject = design(arrayObject,8000000000,Element1);

%Element1 Properties Changed
arrayObject.Element(1).Length = 0.012;
arrayObject.Element(1).Width = 0.009;
arrayObject.Element(1).Height = 0.00155;
arrayObject.Element(1).FeedOffset = [0.003 0];
% Update substrate properties 
arrayObject.Element(1).Substrate.Name = 'RO4350B';
arrayObject.Element(1).Substrate.EpsilonR = 3.48;
arrayObject.Element(1).Substrate.LossTangent = 0.0037;
arrayObject.Element(1).Substrate.Thickness = 0.00155;

%% Array Analysis 
% Show for rectangularArray
figure(1);
show(arrayObject) 
% Layout for rectangularArray
figure(2);
layout(arrayObject) 

figure(3);
show(arrayObject.Element(1))