frequency = 10*10^9;                    % 10 GHz
speed_of_light = 299792458;             % speed of light ~= 3*10^8 m/s
wave_length = speed_of_light/frequency;
d = wave_length/2;

%element = patchMicrostrip;

%array = rectangularArray('Element', element);
%array.Size = [4,4];
%layout(array);
%show(array);

%%
% Create a rectangularArray with patchMicrostrip element.
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 24-Sep-2021 18:02:28

%% Antenna Properties 
% Design antenna at frequency 8000000000Hz
antennaObject = design(patchMicrostrip,8000000000);
% Properties changed 
antennaObject.Length = 0.012;
antennaObject.Width = 0.009;
antennaObject.Height = 0.00155;
antennaObject.GroundPlaneLength = 0.0187;
antennaObject.GroundPlaneWidth = 0.0187;
antennaObject.FeedOffset = [0.003 0];
% Update substrate properties 
antennaObject.Substrate.Name = 'Air';
antennaObject.Substrate.EpsilonR = 3.48;
antennaObject.Substrate.LossTangent = 0.0037;
antennaObject.Substrate.Thickness = 0.00155;


%% Array Properties 

%SubObject = design(patchMicrostrip, 10*1e9);
SubObject = antennaObject;
arrayObject = design(rectangularArray('Element', SubObject), 10*1e9, SubObject);
arrayObject.Element.Substrate.Name = 'FR4';
arrayObject.Element.Substrate.EpsilonR = 4.8;
arrayObject.Element.Substrate.LossTangent = 0.026;
arrayObject.Size = [4, 4];
% arrayObject.RowSpacing = 0.019951;
% arrayObject.ColumnSpacing = 0.019951;
arrayObject.RowSpacing = d;
arrayObject.ColumnSpacing = d;
%arrayObject.PhaseShift = (360/2*pi).*[-0.0,  -2.09584502,  -4.19169004,  -6.28753507,...
%                        -2.09584502,  -4.19169004,  -6.28753507,  -8.38338009,...
%                        -4.19169004,  -6.28753507,  -8.38338009, -10.47922511,...
%                        -6.28753507,  -8.38338009, -10.47922511, -12.57507013];

%% Array Analysis 
% Show for rectangularArray
figure;
show(arrayObject) 
% Layout for rectangularArray
figure;
layout(arrayObject) 
% Array factor for rectangularArray
%arrayFactor(arrayObject, 10*1e9)

%% Antenna pattern
freq = 8*1e9;

[pat, azimuth, elevation] =  pattern(antennaObject, frequency);

%% Pattern multiplication
[fieldval,azimuth,elevation] = patternMultiply(arrayObject,frequency);

%% PatternNC for rectangularArray
% WARNING: COMPUTATIONALLY INTENSIVE!
PlotFrequency = 10*1e9;
figure;
patternMultiply(arrayObject, PlotFrequency) 

%% AzimuthNC for rectangularArray
% WARNING: COMPUTATIONALLY INTENSIVE!
%PlotFrequency = 10*1e9;azRange = 0:5:360;
%figure;
%patternMultiply(arrayObject, PlotFrequency, azRange, 0) 

%% ElevationNC for rectangularArray
% WARNING: COMPUTATIONALLY INTENSIVE!
%PlotFrequency = 10*1e9;elRange = 0:5:360;
%figure;
%patternMultiply(arrayObject, PlotFrequency, 0, elRange)