% Create a patchMicrostrip antenna
% Generated by MATLAB(R) 9.9 and Antenna Toolbox 4.3.
% Generated on: 13-Oct-2021 16:04:44

%% Antenna Properties 
% Design antenna at frequency 8000000000Hz
antennaObject = design(patchMicrostrip,8000000000);
% Properties changed 
antennaObject.Length = 0.012;
antennaObject.Width = 0.009;
antennaObject.Height = 0.00155;
antennaObject.GroundPlaneLength = 0.0187;
antennaObject.GroundPlaneWidth = 0.0187;
antennaObject.FeedOffset = [0.003 0];
% Update substrate properties 
antennaObject.Substrate.Name = 'Air';
antennaObject.Substrate.EpsilonR = 3.48;
antennaObject.Substrate.LossTangent = 0.0037;
antennaObject.Substrate.Thickness = 0.00155;

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 8000000000;
% Define frequency range 
freqRange = (7200:80:8800) * 1e6;
% show for patchMicrostrip
figure;
show(antennaObject) 
% s11 for patchMicrostrip
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s) 

